CONFIG_NAME: 'VGG19'
DATASET_NAME: SVHN
SEED: 1234

# Hyperparameters related to model training
TRAIN:
  VALID_SPLIT: [0.85, 1] # [train_split, extra_split]
  CURRENT_EPOCH: 0
  SAMPLE_SIZE: [-1, -1] # Number of samples to use (for debugging purposes), set to -1 to use the entire dataset ([train_size, extra_size] )
  BATCH_SIZE: 22
  NUM_EPOCHS: 100
  LR: 0.0003
  MOM: 0.9
  WEIGHT_DECAY: 0.0005



