CONFIG_NAME: 'VGG19'
DATASET_NAME: SVHN
SEED: 1234

# Hyperparameters related to model training
TRAIN:
  DATASET_SPLIT: 'train+extra'
  VALID_SPLIT: [0.8, 1]
  CURRENT_EPOCH: 0
  SAMPLE_SIZE: [-1,-1] # Number of samples to use (for debugging purposes), set to -1 to use the entire dataset
  BATCH_SIZE: 32
  STRATIFIED: False
  NUM_EPOCHS: 10
  LR: 0.001
  MOM: 0.9
  SHUFFLE: False
  WEIGHT_DECAY: 0.005
  DECAY_STEPS: 500
  DECAY_RATE: 0.9



